security:
    oauth2:
        client:
            clientId: 180195895689-qnhlgf2neb3ufctd3e3hkhqvo56t1s7u.apps.googleusercontent.com
            clientSecret: gIpGuWY_yn8Min3tvNsBMNd5
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope: profile
        resource:
            userInfoUri: https://www.googleapis.com/userinfo/v2/me
            preferTokenInfo: false